// Code generated by a template
#pragma once
#include "..\export.h"

#include <pcl/pcl_base.h>
#include <pcl/point_types.h>
#include <memory>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(void) pclbase_xyz_setInputCloud(PCLBase<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(std::shared_ptr<PointCloud<PointXYZ>>(cloud, [](PointCloud<PointXYZ>*) {}));
}

EXPORT(void) pclbase_xyz_setIndices(PCLBase<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(std::shared_ptr<vector<int>>(indices, [](vector<int>*) {}));
}

EXPORT(const PointXYZ*) pclbase_xyz_indexGet(PCLBase<PointXYZ>* ptr, int idx)
{ return &ptr->operator[](idx); }

#ifdef __cplusplus  
}
#endif  
