// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/extract_indices.h>
#include <memory>

using namespace pcl;
using namespace std;

typedef ExtractIndices<PointXYZ> filter_t;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(filter_t*) filters_extractIndices_xyz_ctor(bool extractRemovedIndices)
{
	return new filter_t(extractRemovedIndices);
}

EXPORT(void) filters_extractIndices_xyz_delete(filter_t** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_extractIndices_xyz_filter(ExtractIndices<PointXYZ>* ptr, PointCloud<PointXYZ>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_extractIndices_xyz_setInputCloud(ExtractIndices<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(std::shared_ptr<PointCloud<PointXYZ>>(cloud, [](PointCloud<PointXYZ>*) {}));
}

EXPORT(void) filters_extractIndices_xyz_setIndices(ExtractIndices<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(std::shared_ptr<vector<int>>(indices, [](vector<int>*) {}));
}

EXPORT(void) filters_extractIndices_xyz_setKeepOrganized(ExtractIndices<PointXYZ>* ptr, int value)
{ ptr->setKeepOrganized(value); }
EXPORT(int) filters_extractIndices_xyz_getKeepOrganized(ExtractIndices<PointXYZ>* ptr)
{ return ptr->getKeepOrganized(); }

EXPORT(void) filters_extractIndices_xyz_setNegative(ExtractIndices<PointXYZ>* ptr, int value)
{ ptr->setNegative(value); }
EXPORT(int) filters_extractIndices_xyz_getNegative(ExtractIndices<PointXYZ>* ptr)
{ return ptr->getNegative(); }

#ifdef __cplusplus  
}
#endif  
