// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/voxel_grid.h>
#include <memory>

using namespace pcl;
using namespace std;

typedef VoxelGrid<PointXYZ> voxel_grid;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(voxel_grid*) filters_voxelGrid_xyz_ctor()
{
	return new voxel_grid();
}

EXPORT(void) filters_voxelGrid_xyz_delete(voxel_grid** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_voxelGrid_xyz_filter(VoxelGrid<PointXYZ>* ptr, PointCloud<PointXYZ>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_voxelGrid_xyz_setInputCloud(VoxelGrid<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(std::shared_ptr<PointCloud<PointXYZ>>(cloud, [](PointCloud<PointXYZ>*) {}));
}

EXPORT(void) filters_voxelGrid_xyz_setIndices(VoxelGrid<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(std::shared_ptr<vector<int>>(indices, [](vector<int>*) {}));
}

EXPORT(void) filters_voxelGrid_xyz_getLeafSize(VoxelGrid<PointXYZ>* ptr, float* x, float* y, float* z)
{
	auto size = ptr->getLeafSize();
	*x = size[0]; *y = size[1]; *z = size[2];
}

EXPORT(void) filters_voxelGrid_xyz_setLeafSize(VoxelGrid<PointXYZ>* ptr, PointXYZ size)
{
	ptr->setLeafSize(Eigen::Vector4f(size.x, size.y, size.z, 1));
}

EXPORT(void) filters_voxelGrid_xyz_setFilterFieldName(VoxelGrid<PointXYZ>* ptr, const char* str)
{ ptr->setFilterFieldName(string(str)); }

EXPORT(void) filters_voxelGrid_xyz_getFilterFieldName(VoxelGrid<PointXYZ>* ptr, char* str, int dstSz)
{ strcpy_s(str, dstSz, ptr->getFilterFieldName().c_str()); }

EXPORT(void) filters_voxelGrid_xyz_getFilterLimits(VoxelGrid<PointXYZ>* ptr, double* min, double* max)
{ ptr->getFilterLimits(*min, *max); }

EXPORT(void) filters_voxelGrid_xyz_setFilterLimits(VoxelGrid<PointXYZ>* ptr, double min, double max)
{ ptr->setFilterLimits(min, max); }

EXPORT(void) filters_voxelGrid_xyz_setDownsampleAllData(VoxelGrid<PointXYZ>* ptr, int value)
{ ptr->setDownsampleAllData(value); }
EXPORT(int) filters_voxelGrid_xyz_getDownsampleAllData(VoxelGrid<PointXYZ>* ptr)
{ return ptr->getDownsampleAllData(); }

EXPORT(void) filters_voxelGrid_xyz_setMinimumPointsNumberPerVoxel(VoxelGrid<PointXYZ>* ptr, int value)
{ ptr->setMinimumPointsNumberPerVoxel(value); }
EXPORT(int) filters_voxelGrid_xyz_getMinimumPointsNumberPerVoxel(VoxelGrid<PointXYZ>* ptr)
{ return ptr->getMinimumPointsNumberPerVoxel(); }

EXPORT(void) filters_voxelGrid_xyz_getMinBoxCoordinates(VoxelGrid<PointXYZ>* ptr, int* x, int* y, int* z)
{
	auto v = ptr->getMinBoxCoordinates();
	*x = v[0]; *y = v[1]; *z = v[2];
}

EXPORT(void) filters_voxelGrid_xyz_getMaxBoxCoordinates(VoxelGrid<PointXYZ>* ptr, int* x, int* y, int* z)
{
	auto v = ptr->getMaxBoxCoordinates();
	*x = v[0]; *y = v[1]; *z = v[2];
}

EXPORT(void) filters_voxelGrid_xyz_getNrDivisions(VoxelGrid<PointXYZ>* ptr, int* x, int* y, int* z)
{
	auto v = ptr->getNrDivisions();
	*x = v[0]; *y = v[1]; *z = v[2];
}

EXPORT(void) filters_voxelGrid_xyz_getDivisionMultiplier(VoxelGrid<PointXYZ>* ptr, int* x, int* y, int* z)
{
	auto v = ptr->getDivisionMultiplier();
	*x = v[0]; *y = v[1]; *z = v[2];
}

#ifdef __cplusplus  
}
#endif  
